- name: nginx gpg key
  copy: src=files/RPM-GPG-KEY-nginx dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx

- name: nginx repo
  yum_repository:
    name: nginx
    description: nginx stable
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-nginx
    gpgcheck: yes

- name: install nginx
  yum: name=nginx state=present

- name: nginx ssl directory
  file: path=/etc/nginx/ssl state=directory mode=0750

#TODO: custom default page/vhost
- name: nginx ipv6 default fix
  lineinfile: dest=/etc/nginx/conf.d/default.conf
              insertafter="listen[ ]+80;"
              line="    listen [::]:80 ipv6only=on default_server;"

- name: enable/start nginx
  service: name=nginx state=running enabled=true

- name: nginx redirect vhosts
  template: src=templates/redirect.j2 dest=/etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: "{{ redirect_sites }}"
  notify: restart nginx

- name: firewalld http
  firewalld: service=http permanent=true immediate=true state=enabled

- name: firewalld https
  firewalld: service=https permanent=true immediate=true state=enabled

- name: EPEL repo
  yum: name=epel-release state=present

- name: install certbot
  yum: name=certbot state=present
