- name: Generate passphrase
  command: openssl genrsa -des3 -passout pass:x -out /tmp/pass.key 2048

- name: Generate key
  command: openssl rsa -passin pass:x -in /tmp/pass.key -out /etc/nginx/ssl/{{ site }}.key
           creates=/etc/nginx/ssl/{{ site }}.key

- name: Generate CSR
  command: |
    openssl req -new -key /etc/nginx/ssl/{{ site }}.key -out /etc/nginx/ssl/{{ site }}.csr
    -subj '/C=US/ST=Indiana/L=Gary/O=Self Signed R Us/OU=IT/CN={{ site }}'
    creates=/etc/nginx/ssl/{{ site }}.csr

- name: Generate self-signed cert
  command: |
    openssl x509 -req -sha256 -days 365 -in /etc/nginx/ssl/{{ site }}.csr
    -signkey /etc/nginx/ssl/{{ site }}.key -out /etc/nginx/ssl/{{ site }}.crt
    creates=/etc/nginx/ssl/{{ site }}.crt
