- name: Check if wp-cli is installed
  stat: path=/usr/local/bin/wp
  register: wpcli_bin

- name: fetch wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
           dest=/usr/local/bin/wp mode=0755
  when: wpcli_bin.stat.exists == False

- include: tasks/selfsign.yml site={{ item.key }}
  with_dict: "{{ wp_sites }}"
  when: inventory_hostname in item.value.hosts

- include: tasks/structure.yml
  with_dict: "{{ wp_sites }}"
  when: inventory_hostname in item.value.hosts

- include: tasks/install.yml
  with_dict: "{{ wp_sites }}"
  become: true
  become_user: "{{ wp_user }}"
  when: inventory_hostname in item.value.hosts
