- name: EPEL repo
  yum: name=epel-release state=present

- name: Standard packages
  yum: name={{ item }} state=present
  with_items:
    - net-tools
    - whois
    - wget
    - rsync
    - openssh-clients
    - xmlstarlet
    - ansible
    - git
    - pwgen
    - fail2ban
    - fail2ban-systemd

- name: Disable root SSH logins
  lineinfile: dest=/etc/ssh/sshd_config state=present
              insertafter="#PermitRootLogin"
              line="PermitRootLogin no"
  notify: restart sshd

- name: fail2ban jail.local
  copy: src=files/jail.local dest=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - firewalld
    - sshd
    - fail2ban
