redirect_sites:
  ohay.org:
    hosts:
      - linode.ohay.org
    redirect: www.ohay.org


wp_user: nicole
wp_group: nicole

wp_sites:
  www.ohay.org:
    hosts:
      - linode.ohay.org
    db_name: ohay_wp
    db_user: ohay_wp_user
#    db_pass: defined in vault_sites.yml
    admin_user: ghopper
#    admin_pass: defined in vault_sites.yml
    admin_email: tty@ohay.org
    editor_user: nicole
#    editor_pass: defined in vault_sites.yml
    editor_email: nicole@ohay.org
    title: ohay
    theme: unite
  wpdev.lan:
    hosts:
      - wpdev
    db_name: ohay_dev
    db_user: ohay_dev_user
#    db_pass: defined in vault_sites.yml
    admin_user: ghopper
#    admin_pass: defined in vault_sites.yml
    admin_email: tty@ohay.org
    editor_user: nicole
#    editor_pass: defined in vault_sites.yml
    editor_email: nicole@ohay.org
    title: ohay_dev
    theme: unite
